новый файл:    task1_1_2/Find_substring/.idea/.gitignore
Inikta/OOP pull request #1
Opened 2021-10-01 12:12 UTC by Inikta

новый файл:    task1_1_2/Find_substring/.idea/compiler.xml
	новый файл:    task1_1_2/Find_substring/.idea/gradle.xml
	новый файл:    task1_1_2/Find_substring/.idea/jarRepositories.xml
	новый файл:    task1_1_2/Find_substring/.idea/misc.xml
	новый файл:    task1_1_2/Find_substring/.idea/runConfigurations.xml
	новый файл:    task1_1_2/Find_substring/.idea/vcs.xml
	новый файл:    task1_1_2/Find_substring/build.gradle
	новый файл:    task1_1_2/Find_substring/emptyTest.txt
	новый файл:    task1_1_2/Find_substring/gradle/wrapper/gradle-wrapper.jar
	новый файл:    task1_1_2/Find_substring/gradle/wrapper/gradle-wrapper.properties
	новый файл:    task1_1_2/Find_substring/gradlew
	новый файл:    task1_1_2/Find_substring/gradlew.bat
	новый файл:    task1_1_2/Find_substring/settings.gradle
	новый файл:    task1_1_2/Find_substring/shortTextTest.txt
	новый файл:    task1_1_2/Find_substring/src/main/java/ru/nsu/nikita/App.java
	новый файл:    task1_1_2/Find_substring/src/main/java/ru/nsu/nikita/FindSubstring.java
	новый файл:    task1_1_2/Find_substring/src/test/java/ru/nsu/nikita/FindInFileTestPack.java
	новый файл:    task1_1_2/Find_substring/src/test/java/ru/nsu/nikita/FindInStringTestPack.java

2021-10-01 14:40 UTC, Leidenn2509 requested changes
Оставил пару замечаний по коду. 
Основная проблема это дублирование кода. Необходимо вынести логику поиска паттерна в отдельную функцию. Я предлагаю вам вынести код поиска патерна в функцию `int find(Reader reader, String pattern)`. А в функциях `findInString` `findInFile` вызывать функцию `find`

2021-10-01 14:40 UTC, Leidenn2509 commented on task1_1_2/Find_substring/src/main/java/ru/nsu/nikita/FindSubstring.java
> +        if (inFileName != null) {
Если имя файла не задано то можно сразу выйти.

2021-10-01 14:40 UTC, Leidenn2509 commented on task1_1_2/Find_substring/src/test/java/ru/nsu/nikita/FindInFileTestPack.java
> +    void TextTest () throws IOException {
Имя должно быть `lowerCamelCase`

2021-10-01 14:41 UTC, Leidenn2509 commented
Мягкий дедлайн зачёл

2021-10-03 04:31 UTC, Inikta commented
Изменил основной файл FindSubstring.java. Повторяющийся алгоритм теперь вынесен в отдельную функцию  findSubstring. Выход при нулевом имени файла не стал добавлять.

2021-10-05 07:34 UTC, Leidenn2509 approved these changes

2021-10-05 07:34 UTC, merged