Третья лабораторная работа (свой стэк).
Inikta/OOP pull request #2
Opened 2021-10-16 17:30 UTC by Inikta

новый файл:    task1_2_1/.idea/compiler.xml
	новый файл:    task1_2_1/.idea/gradle.xml
	новый файл:    task1_2_1/.idea/jarRepositories.xml
	новый файл:    task1_2_1/.idea/misc.xml
	новый файл:    task1_2_1/.idea/vcs.xml
	новый файл:    task1_2_1/build.gradle
	новый файл:    task1_2_1/gradle/wrapper/gradle-wrapper.jar
	новый файл:    task1_2_1/gradle/wrapper/gradle-wrapper.properties
	новый файл:    task1_2_1/gradlew
	новый файл:    task1_2_1/gradlew.bat
	новый файл:    task1_2_1/settings.gradle
	новый файл:    task1_2_1/src/main/java/ru/nsu/nikita/MyStack.java
	новый файл:    task1_2_1/src/main/java/ru/nsu/nikita/StackIterator.java
	новый файл:    task1_2_1/src/test/java/ru/nsu/nikita/Dot.java
	новый файл:    task1_2_1/src/test/java/ru/nsu/nikita/MyStackTests.java

2021-10-16 21:21 UTC, Leidenn2509 requested changes
Код плохо отформатирован. Используйте `ctrl+alt+l`, если в Intellij IDEA.
И не игнорируйте ворнинги которые вам выдаёт ide.

2021-10-16 21:21 UTC, Leidenn2509 commented on task1_2_1/src/main/java/ru/nsu/nikita/StackIterator.java
> +    private int amount;     //size of array
`Field 'amount' may be 'final' `

2021-10-16 21:21 UTC, Leidenn2509 commented on task1_2_1/src/main/java/ru/nsu/nikita/StackIterator.java
> +    private T[] stackArr;
Field 'stackArr' may be 'final'

2021-10-16 21:21 UTC, Leidenn2509 commented on task1_2_1/src/main/java/ru/nsu/nikita/StackIterator.java
> +        this.stackArr = (T[]) someStack.getStack();
Ненужный каст. Функция у вас и так возвращает `T[]`

2021-10-16 21:21 UTC, Leidenn2509 commented on task1_2_1/src/main/java/ru/nsu/nikita/StackIterator.java
> +        if (hasCnt < amount) {      //if next element exists, return true
Не совсем понимаю для чего этот счётчик и как работает метод `hasNext`.
Почему когда элементы закончились вы обнуляете счётчик `hasCnt`? Ведь вы не двигаете итератор на нулевой элемент. 
Задача этого метода просто сказать есть там элемент ещё или нет. Ваш же метод не выполняет эту задачу. Пока вы не вызвали `next` итератор не "двигается".

2021-10-16 21:21 UTC, Leidenn2509 commented on task1_2_1/src/main/java/ru/nsu/nikita/StackIterator.java
> +        else {
style

2021-10-16 21:21 UTC, Leidenn2509 commented on task1_2_1/src/main/java/ru/nsu/nikita/StackIterator.java
> +        else {
style

2021-10-16 21:21 UTC, Leidenn2509 commented on task1_2_1/src/main/java/ru/nsu/nikita/StackIterator.java
> +        if (cnt < amount) {         //if next element exists, return it
Для такой проверки у вас есть написанный вами метод `hasNext`

2021-10-16 21:21 UTC, Leidenn2509 commented on task1_2_1/src/test/java/ru/nsu/nikita/Dot.java
> +    public Dot (int a, int b) {
style

2021-10-16 21:21 UTC, Leidenn2509 commented on task1_2_1/src/test/java/ru/nsu/nikita/MyStackTests.java
> +        MyStack <Dot> stack = new MyStack<>();
Строчка повторяется. Вынесите её в метод помеченный аннотацией `@BeforeEach`

2021-10-16 21:21 UTC, Leidenn2509 commented on task1_2_1/src/test/java/ru/nsu/nikita/MyStackTests.java
> +    void CounterTest () {
naming

2021-10-16 21:21 UTC, Leidenn2509 commented on task1_2_1/src/test/java/ru/nsu/nikita/MyStackTests.java
> +        }
Используйте `for`

2021-10-17 04:44 UTC, Inikta commented
Не привык еще подписывать коммиты: первый - это основные исправления, второй - это тоже самое, но с автоформатированием. Забыл сразу отформатировать.

2021-10-17 20:26 UTC, Leidenn2509 requested changes
В классе `Dot` всё ещё плохие пробелы
В итераторе лишний `/n`
И у вас в ветку утекли файлы следующей лабы

2021-10-17 20:26 UTC, Leidenn2509 commented on task1_2_1/src/main/java/ru/nsu/nikita/MyStack.java
> +        return (T[]) res;
`Arrays.copyOf`

2021-10-17 20:26 UTC, Leidenn2509 commented on task1_2_1/src/main/java/ru/nsu/nikita/StackIterator.java
>          else {
Должно быть 
```java
} else {
```

2021-10-18 13:06 UTC, merged