Лабораторная работа №7. Дерево.
Inikta/OOP pull request #7
Opened 2021-12-12 15:20 UTC by Inikta

new file:   task1_2_2/.idea/compiler.xml
	new file:   task1_2_2/.idea/gradle.xml
	new file:   task1_2_2/.idea/jarRepositories.xml
	new file:   task1_2_2/.idea/misc.xml
	new file:   task1_2_2/.idea/runConfigurations.xml
	new file:   task1_2_2/.idea/uiDesigner.xml
	new file:   task1_2_2/build.gradle
	new file:   task1_2_2/gradle/wrapper/gradle-wrapper.jar
	new file:   task1_2_2/gradle/wrapper/gradle-wrapper.properties
	new file:   task1_2_2/gradlew
	new file:   task1_2_2/gradlew.bat
	new file:   task1_2_2/settings.gradle
	new file:   task1_2_2/src/main/java/ru/nsu/nikita/TreeNode.java
	new file:   task1_2_2/src/main/java/ru/nsu/nikita/TreeNodeIterator.java

2021-12-14 13:24 UTC, Inikta commented
Удалил прошлую версию дерева и добавил новую (ту которую показывал на семинаре).

2021-12-17 10:47 UTC, Leidenn2509 requested changes
- Лишняя папка для лабы
- javadoc
- Ну и побольше тестов, как минимум тест из примера к заданию

2021-12-17 10:47 UTC, Leidenn2509 commented on task1_2_2v3/task1_2_2v3/src/main/java/ru/nsu/nikita/TreeNode.java
> +    public TreeNode(T content, TreeNode<T> parent) {
Сделайте ещё конструктор только с контентом

2021-12-17 10:47 UTC, Leidenn2509 commented on task1_2_2v3/task1_2_2v3/src/main/java/ru/nsu/nikita/TreeNode.java
> +        this.parent = parent;
Связь родитель-ребенок двустороняя. Если вы изменили родителя у ноды, надо удалить его из детей предыдущего родителя, и добавить как ребенка к новому

2021-12-17 10:47 UTC, Leidenn2509 commented on task1_2_2v3/task1_2_2v3/src/main/java/ru/nsu/nikita/TreeNode.java
> +public class TreeNode<T> {
Должна быть возможность добавить одного ребенка

2021-12-17 10:47 UTC, Leidenn2509 commented on task1_2_2v3/task1_2_2v3/src/main/java/ru/nsu/nikita/TreeSettings.java
> +    public enum insertSetting {no, insertBeforeSingle, insertBeforeBunch}
https://google.github.io/styleguide/javaguide.html

2021-12-17 10:47 UTC, Leidenn2509 commented on task1_2_2v3/task1_2_2v3/src/main/java/ru/nsu/nikita/SearchAlgorithms.java
> +public class SearchAlgorithms<T> {
Попробуйте переписать алогритмы итеративно

2021-12-17 10:47 UTC, Leidenn2509 commented on task1_2_2v3/task1_2_2v3/src/main/java/ru/nsu/nikita/Tree.java
> +public class Tree<T> implements Iterable<T> {
Должна быть возможность получить поддерево.
Я советую убрать обертку `Tree` и использовать только `TreeNode`

2021-12-17 10:47 UTC, Leidenn2509 commented on task1_2_2v3/task1_2_2v3/src/main/java/ru/nsu/nikita/TreeIterator.java
> +        try {rightNeighbor = tree.getNodesList().get(nextIndex());}
Лучше всё же просто проверить индекс через `if`

2021-12-17 10:47 UTC, Leidenn2509 commented on task1_2_2v3/task1_2_2v3/src/main/java/ru/nsu/nikita/TreeIterator.java
> +                    }
Дублирование кода

2021-12-17 10:47 UTC, Leidenn2509 commented on task1_2_2v3/task1_2_2v3/src/main/java/ru/nsu/nikita/Tree.java
> +    public TreeIterator<T> iterator() {
Хочется чтобы итератор итерировался по узлам, а не по их значениям

2021-12-27 14:57 UTC, Leidenn2509 approved these changes

2021-12-27 14:57 UTC, merged